### ISSUE TITLE
Get patient homepage able to grab a list of patients.

### ISSUE THREAD

**Issue by hungaud** [hungaud/PhysicalTherapy#11]

**Comment by AlexLeathers** [comment]
What is this issue supposed to be? Is this for making the patient homepage? I'm not sure why we'd want to grab a list of patients from the patient homepage.

**Comment by hungaud** [comment]
Oops meant to say routine

**Comment by AlexLeathers** [comment]
Okay, so just mock routines like we did with patients for the therapist?

**Comment by hungaud** [comment]
Yes, grab list of routines
